#spring web
server:
  port: 80      #配置端口号为80
  servlet:
    context-path: /     #配置请求路径项目名称为/
  tomcat:
    max-threads: 1000   #配置tomcat请求线程最大数
  
#spring datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jtsys?serverTimezone=GMT%2B8
    username: root
    password: root
  thymeleaf:
    cache: false    #配置html文件修改后，自动部署
    prefix: classpath:/templates/pages/
    suffix: .html
  
#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30     #配置mybatis请求超过30ms自动断开
    map-underscore-to-camel-case: true    #配置表格字段中的_自动替换为驼峰命名
  mapper-locations:
  - classpath:/mapper/sys/*/*.xml
  
#log
logging:
  level:
    com.cy: debug       #配置log4j，在控制台打印sql语句    
